AZURE_STORAGE_ACCOUNT_NAME = "stcandidatedev"
AZURE_STORAGE_ACCOUNT_KEY = "7j9fQrp2GBUlBJJjEFu1LrKNIaVKD73MTRin+hRsP1R8tdiasOkg7H3if5bJQfHNwdkw2NoBjdez+ASt9IbpRw=="
AZURE_STORAGE_CONTAINER = "landing"