# Azure Blob Storage Configuration
[azure]
storage_account_name = "stcandidatedev"
storage_account_key = "7j9fQrp2GBUlBJJjEFu1LrKNIaVKD73MTRin+hRsP1R8tdiasOkg7H3if5bJQfHNwdkw2NoBjdez+ASt9IbpRw=="
container_name = "landing"  # This matches the required container name



